export const ApiError = {
  ROLE_NOT_FOUND: "Role was not found",
  POST_LIKED: "You already liked the post",
  USER_EXIST: "User with this email already exist",
  USER_NOT_FOUND: "User was not found",
  WRONG_DATA: "Email or password is not correct",
  INVALID_CODE: "The code is invalid or expired",
  WRONG_ROLE: "You have not the right role",
  EMPLOYEE_NOT_FOUND: "Employee was not found",
  RESUME_NOT_FOUND: "Resume was not found",
  EMPLOYER_NOT_FOUND: "Employer was not found",
  JOB_POST_NOT_FOUND: "Job post was not found",
  JOB_APPLICATION_NOT_FOUND: "Job application was not found",
  RESUME_APPLICATION_NOT_FOUND: "Resume application was not found",
  EMPLOYER_REVIEW_NOT_FOUND: "Employer review was not found",
}
